<?php

namespace AppBundle\Repository;

/**
 * OrderingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLink($link){
        return $this->findOneBy(['link'=>$link]);
    }
}
