#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

app_ordering:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
#    defaults: { _locale: '%locale%'}

homepage_without_locale:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  [GET,POST]
    defaults: { _locale: '%locale%'}


