
#------------------ fos_user --------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


#---------------------------------------------------
ordering_finish2:
    path:     /ordering_finish2
    defaults: { _controller: "AppBundle:Default:orderingFinish2"}
    methods: [GET,POST]

ordering_details:
    path:     /ordering_details/{link}
    defaults: { _controller: "AppBundle:Default:orderingDetails"}
    methods: [GET,POST]
ordering_message_ajax:
    path:     /message_ajax
    defaults: { _controller: "AppBundle:Ordering:messageAjax" }
    methods:  [GET, POST]
homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  [GET,POST]



app_ordering:
    resource: "@AppBundle/Resources/config/routing/ordering.yml"
    prefix:   /admin/ordering

app_visit:
    resource: "@AppBundle/Resources/config/routing/visit.yml"
    prefix:   /admin/visit

